//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8794
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC.iNet.DS.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ConsoleServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ConsoleServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISC.iNet.DS.Services.Resources.ConsoleServiceResources", typeof(ConsoleServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings.
        /// </summary>
        internal static string BACKING_UP_SETTINGS {
            get {
                return ResourceManager.GetString("BACKING_UP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Failure.
        /// </summary>
        internal static string BUMPFAILURE {
            get {
                return ResourceManager.GetString("BUMPFAILURE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bump Failure ({0}) Check Gas Connections.
        /// </summary>
        internal static string BUMPFAILURECHECKGASCONNECTION {
            get {
                return ResourceManager.GetString("BUMPFAILURECHECKGASCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Instrument.
        /// </summary>
        internal static string BUMPINGINSTRUMENT {
            get {
                return ResourceManager.GetString("BUMPINGINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Stopped (Check Pump Tubing).
        /// </summary>
        internal static string BUMPSTOPPEDCHECKTUBING {
            get {
                return ResourceManager.GetString("BUMPSTOPPEDCHECKTUBING", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating.
        /// </summary>
        internal static string CALIBRATINGINSTRUMENT {
            get {
                return ResourceManager.GetString("CALIBRATINGINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Failure.
        /// </summary>
        internal static string CALIBRATIONFAILURE {
            get {
                return ResourceManager.GetString("CALIBRATIONFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Stopped (Check Pump Tubing).
        /// </summary>
        internal static string CALIBRATIONSTOPPEDCHECKTUBING {
            get {
                return ResourceManager.GetString("CALIBRATIONSTOPPEDCHECKTUBING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone.
        /// </summary>
        internal static string CALSTATION {
            get {
                return ResourceManager.GetString("CALSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        internal static string CHARGING {
            get {
                return ResourceManager.GetString("CHARGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Cylinder Connections.
        /// </summary>
        internal static string CHECKCYLINDERCONNECTIONS {
            get {
                return ResourceManager.GetString("CHECKCYLINDERCONNECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Available Gas.
        /// </summary>
        internal static string CHECKINGGAS {
            get {
                return ResourceManager.GetString("CHECKINGGAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Alarm Events.
        /// </summary>
        internal static string CLEARINGINSTRUMENTALARMEVENTS {
            get {
                return ResourceManager.GetString("CLEARINGINSTRUMENTALARMEVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Datalog.
        /// </summary>
        internal static string CLEARINGINSTRUMENTDATALOG {
            get {
                return ResourceManager.GetString("CLEARINGINSTRUMENTDATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Manual Operations.
        /// </summary>
        internal static string CLEARINGINSTRUMENTMANUALGASOPERATIONS {
            get {
                return ResourceManager.GetString("CLEARINGINSTRUMENTMANUALGASOPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Fresh Air Or Zero Air to Port 1.
        /// </summary>
        internal static string CONNECTFRESHAIRORZEROAIRTOPORT1 {
            get {
                return ResourceManager.GetString("CONNECTFRESHAIRORZEROAIRTOPORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Fresh Air to Port 1.
        /// </summary>
        internal static string CONNECTFRESHAIRTOPORT1 {
            get {
                return ResourceManager.GetString("CONNECTFRESHAIRTOPORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Zero Air Cylinder.
        /// </summary>
        internal static string CONNECTTOZEROAIRCYLINDER {
            get {
                return ResourceManager.GetString("CONNECTTOZEROAIRCYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Zero Air to Port 1.
        /// </summary>
        internal static string CONNECTZEROAIRTOPORT1 {
            get {
                return ResourceManager.GetString("CONNECTZEROAIRTOPORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 101-1.
        /// </summary>
        internal static string CONTACTISCCODE1011 {
            get {
                return ResourceManager.GetString("CONTACTISCCODE1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 101-10.
        /// </summary>
        internal static string CONTACTISCCODE10110 {
            get {
                return ResourceManager.GetString("CONTACTISCCODE10110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 101-2.
        /// </summary>
        internal static string CONTACTISCCODE1012 {
            get {
                return ResourceManager.GetString("CONTACTISCCODE1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 101-4.
        /// </summary>
        internal static string CONTACTISCCODE1014 {
            get {
                return ResourceManager.GetString("CONTACTISCCODE1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 101-60.
        /// </summary>
        internal static string CONTACTISCCODE10160 {
            get {
                return ResourceManager.GetString("CONTACTISCCODE10160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 101-8.
        /// </summary>
        internal static string CONTACTISCCODE1018 {
            get {
                return ResourceManager.GetString("CONTACTISCCODE1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-iGas Pressure Levels Reset to Full.
        /// </summary>
        internal static string CYLINDERPRESSURERESET {
            get {
                return ResourceManager.GetString("CYLINDERPRESSURERESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosing.
        /// </summary>
        internal static string DIAGNOSING {
            get {
                return ResourceManager.GetString("DIAGNOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosing Instrument.
        /// </summary>
        internal static string DIAGNOSINGINSTRUMENT {
            get {
                return ResourceManager.GetString("DIAGNOSINGINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering.
        /// </summary>
        internal static string DISCOVERING {
            get {
                return ResourceManager.GetString("DISCOVERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Station.
        /// </summary>
        internal static string DOCKINGSTATION {
            get {
                return ResourceManager.GetString("DOCKINGSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Alarm Events.
        /// </summary>
        internal static string DOWNLOADINGINSTRUMENTALARMEVENTS {
            get {
                return ResourceManager.GetString("DOWNLOADINGINSTRUMENTALARMEVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Datalog.
        /// </summary>
        internal static string DOWNLOADINGINSTRUMENTDATALOG {
            get {
                return ResourceManager.GetString("DOWNLOADINGINSTRUMENTDATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Manual Operations.
        /// </summary>
        internal static string DOWNLOADINGINSTRUMENTMANUALGASOPERATIONS {
            get {
                return ResourceManager.GetString("DOWNLOADINGINSTRUMENTMANUALGASOPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Bias State: {0} Secs.
        /// </summary>
        internal static string ELAPSEDBIASSTATE {
            get {
                return ResourceManager.GetString("ELAPSEDBIASSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder Expired.
        /// </summary>
        internal static string EXPIREDCYLINDER {
            get {
                return ResourceManager.GetString("EXPIREDCYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        internal static string EXTRACTING {
            get {
                return ResourceManager.GetString("EXTRACTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to USB drive: FAILED.
        /// </summary>
        internal static string FILEMANAGER_FAILED {
            get {
                return ResourceManager.GetString("FILEMANAGER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to USB drive.
        /// </summary>
        internal static string FILEMANAGER_SAVING {
            get {
                return ResourceManager.GetString("FILEMANAGER_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to USB drive: SUCCEEDED.
        /// </summary>
        internal static string FILEMANAGER_SUCCEEDED {
            get {
                return ResourceManager.GetString("FILEMANAGER_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flipper and Lid Positions.
        /// </summary>
        internal static string FLIPPERANDLIDERROR {
            get {
                return ResourceManager.GetString("FLIPPERANDLIDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Air.
        /// </summary>
        internal static string FRESH_AIR {
            get {
                return ResourceManager.GetString("FRESH_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Air.
        /// </summary>
        internal static string G9999 {
            get {
                return ResourceManager.GetString("G9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Configuration Error.
        /// </summary>
        internal static string HARDWARECONFIGERROR {
            get {
                return ResourceManager.GetString("HARDWARECONFIGERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGas Error.
        /// </summary>
        internal static string IGASERROR {
            get {
                return ResourceManager.GetString("IGASERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Pressure Switches.
        /// </summary>
        internal static string IGASERROR_PRESSURESWITCHES {
            get {
                return ResourceManager.GetString("IGASERROR_PRESSURESWITCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check iGas Cards.
        /// </summary>
        internal static string IGASERROR_SMARTCARDS {
            get {
                return ResourceManager.GetString("IGASERROR_SMARTCARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iNet.
        /// </summary>
        internal static string INET {
            get {
                return ResourceManager.GetString("INET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Not Ready.
        /// </summary>
        internal static string INSTRUMENTNOTREADY {
            get {
                return ResourceManager.GetString("INSTRUMENTNOTREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Error.
        /// </summary>
        internal static string INSTRUMENTSYSTEMALARM {
            get {
                return ResourceManager.GetString("INSTRUMENTSYSTEMALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosing.
        /// </summary>
        internal static string INTERACTIVEDIAGNOSTICS {
            get {
                return ResourceManager.GetString("INTERACTIVEDIAGNOSTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable Leaking.
        /// </summary>
        internal static string LEAKUNAVAILABLE {
            get {
                return ResourceManager.GetString("LEAKUNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid Not Closed.
        /// </summary>
        internal static string LIDERROR {
            get {
                return ResourceManager.GetString("LIDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Low. Waiting To Connect..
        /// </summary>
        internal static string LOWBATTERY {
            get {
                return ResourceManager.GetString("LOWBATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder Low.
        /// </summary>
        internal static string LOWCYLINDER {
            get {
                return ResourceManager.GetString("LOWCYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Failure.
        /// </summary>
        internal static string MANUALBUMPTESTREQUIRED {
            get {
                return ResourceManager.GetString("MANUALBUMPTESTREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Cal Fail Manually Calibrate.
        /// </summary>
        internal static string MANUALCALIBRATIONREQUIRED {
            get {
                return ResourceManager.GetString("MANUALCALIBRATIONREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        internal static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string MENU_ACCOUNT {
            get {
                return ResourceManager.GetString("MENU_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string MENU_ACCOUNTNUMBER {
            get {
                return ResourceManager.GetString("MENU_ACCOUNTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure?.
        /// </summary>
        internal static string MENU_ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("MENU_ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Test.
        /// </summary>
        internal static string MENU_BUMP_TEST {
            get {
                return ResourceManager.GetString("MENU_BUMP_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        internal static string MENU_CALIBRATE {
            get {
                return ResourceManager.GetString("MENU_CALIBRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinders.
        /// </summary>
        internal static string MENU_CYLINDER {
            get {
                return ResourceManager.GetString("MENU_CYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose.
        /// </summary>
        internal static string MENU_DIAGNOSE {
            get {
                return ResourceManager.GetString("MENU_DIAGNOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Station.
        /// </summary>
        internal static string MENU_DOCKINGSTATION {
            get {
                return ResourceManager.GetString("MENU_DOCKINGSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Datalog.
        /// </summary>
        internal static string MENU_DOWNLOAD_HYGIENE {
            get {
                return ResourceManager.GetString("MENU_DOWNLOAD_HYGIENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to.
        /// </summary>
        internal static string MENU_FACTORY_RESET1 {
            get {
                return ResourceManager.GetString("MENU_FACTORY_RESET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string MENU_FACTORY_RESET2 {
            get {
                return ResourceManager.GetString("MENU_FACTORY_RESET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults?.
        /// </summary>
        internal static string MENU_FACTORY_RESET3 {
            get {
                return ResourceManager.GetString("MENU_FACTORY_RESET3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Gas Retry.
        /// </summary>
        internal static string MENU_FORCE_GAS_RETRY {
            get {
                return ResourceManager.GetString("MENU_FORCE_GAS_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iNet.
        /// </summary>
        internal static string MENU_INET {
            get {
                return ResourceManager.GetString("MENU_INET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MENU_INFORMATION {
            get {
                return ResourceManager.GetString("MENU_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument.
        /// </summary>
        internal static string MENU_INSTRUMENT {
            get {
                return ResourceManager.GetString("MENU_INSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string MENU_MORE {
            get {
                return ResourceManager.GetString("MENU_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MENU_NO {
            get {
                return ResourceManager.GetString("MENU_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MENU_PREVIOUS {
            get {
                return ResourceManager.GetString("MENU_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Settings.
        /// </summary>
        internal static string MENU_REFRESH {
            get {
                return ResourceManager.GetString("MENU_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string MENU_SERVER {
            get {
                return ResourceManager.GetString("MENU_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string MENU_TROUBLESHOOT {
            get {
                return ResourceManager.GetString("MENU_TROUBLESHOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MENU_YES {
            get {
                return ResourceManager.GetString("MENU_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No iNet Connection for Manufacturing.
        /// </summary>
        internal static string MFGNOTCONNECTED {
            get {
                return ResourceManager.GetString("MFGNOTCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cylinder.
        /// </summary>
        internal static string NOCYLINDER {
            get {
                return ResourceManager.GetString("NOCYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Enabled Sensors.
        /// </summary>
        internal static string NOENABLEDSENSORS {
            get {
                return ResourceManager.GetString("NOENABLEDSENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not activated.
        /// </summary>
        internal static string NOTACTIVATED {
            get {
                return ResourceManager.GetString("NOTACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 102.
        /// </summary>
        internal static string NOTSERIALIZED {
            get {
                return ResourceManager.GetString("NOTSERIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Maintenance.
        /// </summary>
        internal static string PERFORMINGMAINTENANCE {
            get {
                return ResourceManager.GetString("PERFORMINGMAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Turn On Instrument WITHOUT UNDOCKING.
        /// </summary>
        internal static string PLEASETURNON {
            get {
                return ResourceManager.GetString("PLEASETURNON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position .
        /// </summary>
        internal static string POSITION {
            get {
                return ResourceManager.GetString("POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Error.
        /// </summary>
        internal static string PRINTERERROR {
            get {
                return ResourceManager.GetString("PRINTERERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Connection.
        /// </summary>
        internal static string PRINTERERROR_USBCONNECTION {
            get {
                return ResourceManager.GetString("PRINTERERROR_USBCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSX.
        /// </summary>
        internal static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        internal static string PROGRAMMING {
            get {
                return ResourceManager.GetString("PROGRAMMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging.
        /// </summary>
        internal static string PURGING {
            get {
                return ResourceManager.GetString("PURGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Settings.
        /// </summary>
        internal static string READINGDATA {
            get {
                return ResourceManager.GetString("READINGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Instrument Settings.
        /// </summary>
        internal static string READINGINSTRUMENTDATA {
            get {
                return ResourceManager.GetString("READINGINSTRUMENTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string READY {
            get {
                return ResourceManager.GetString("READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Cylinder.
        /// </summary>
        internal static string REPLACECYLINDER {
            get {
                return ResourceManager.GetString("REPLACECYLINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Settings.
        /// </summary>
        internal static string RESTORING_SETTINGS {
            get {
                return ResourceManager.GetString("RESTORING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Instrument to Industrial Scientific.
        /// </summary>
        internal static string RETURNDISABLEDINSTRUMENT {
            get {
                return ResourceManager.GetString("RETURNDISABLEDINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Docking Station to Industrial Scientific.
        /// </summary>
        internal static string RETURNDOCKINGSTATION {
            get {
                return ResourceManager.GetString("RETURNDOCKINGSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Instrument to Industrial Scientific.
        /// </summary>
        internal static string RETURNINSTRUMENT {
            get {
                return ResourceManager.GetString("RETURNINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string SAVING {
            get {
                return ResourceManager.GetString("SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Error.
        /// </summary>
        internal static string SENSORERROR {
            get {
                return ResourceManager.GetString("SENSORERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO.
        /// </summary>
        internal static string SENSORLABEL_S0001 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2S.
        /// </summary>
        internal static string SENSORLABEL_S0002 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO2.
        /// </summary>
        internal static string SENSORLABEL_S0003 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO2.
        /// </summary>
        internal static string SENSORLABEL_S0004 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL2.
        /// </summary>
        internal static string SENSORLABEL_S0005 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLO2.
        /// </summary>
        internal static string SENSORLABEL_S0006 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCN.
        /// </summary>
        internal static string SENSORLABEL_S0007 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH3.
        /// </summary>
        internal static string SENSORLABEL_S0008 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2.
        /// </summary>
        internal static string SENSORLABEL_S0009 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2.
        /// </summary>
        internal static string SENSORLABEL_S0011 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string SENSORLABEL_S0012 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NH3.
        /// </summary>
        internal static string SENSORLABEL_S0013 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCL.
        /// </summary>
        internal static string SENSORLABEL_S0014 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O3.
        /// </summary>
        internal static string SENSORLABEL_S0015 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COCL2.
        /// </summary>
        internal static string SENSORLABEL_S0016 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HF.
        /// </summary>
        internal static string SENSORLABEL_S0017 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR (CH4).
        /// </summary>
        internal static string SENSORLABEL_S0018 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEL (PPM).
        /// </summary>
        internal static string SENSORLABEL_S0019 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2.
        /// </summary>
        internal static string SENSORLABEL_S0020 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEL (CH4).
        /// </summary>
        internal static string SENSORLABEL_S0021 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEL.
        /// </summary>
        internal static string SENSORLABEL_S0022 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEL (C6H14).
        /// </summary>
        internal static string SENSORLABEL_S0023 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR-LEL (CH4).
        /// </summary>
        internal static string SENSORLABEL_S0024 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEL (C5H12).
        /// </summary>
        internal static string SENSORLABEL_S0026 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEL (C3H8).
        /// </summary>
        internal static string SENSORLABEL_S0027 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        internal static string SENSORLABEL_S0050 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETO.
        /// </summary>
        internal static string SENSORLABEL_S0081 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HC.
        /// </summary>
        internal static string SENSORLABEL_S0248 {
            get {
                return ResourceManager.GetString("SENSORLABEL_S0248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Missing.
        /// </summary>
        internal static string SENSORMISSING {
            get {
                return ResourceManager.GetString("SENSORMISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN:.
        /// </summary>
        internal static string SERIAL_ABBREV {
            get {
                return ResourceManager.GetString("SERIAL_ABBREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Instrument Soon.
        /// </summary>
        internal static string SERVICEINSTRUMENTSOON {
            get {
                return ResourceManager.GetString("SERVICEINSTRUMENTSOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string STARTING {
            get {
                return ResourceManager.GetString("STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        internal static string SYNCHRONIZATION {
            get {
                return ResourceManager.GetString("SYNCHRONIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        internal static string SYNCHRONIZATIONERROR {
            get {
                return ResourceManager.GetString("SYNCHRONIZATIONERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string TROUBLESHOOT {
            get {
                return ResourceManager.GetString("TROUBLESHOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying to USB drive.
        /// </summary>
        internal static string TROUBLESHOOT_COPYING {
            get {
                return ResourceManager.GetString("TROUBLESHOOT_COPYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to USB drive: FAILED.
        /// </summary>
        internal static string TROUBLESHOOT_FAILED {
            get {
                return ResourceManager.GetString("TROUBLESHOOT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB drive not found.
        /// </summary>
        internal static string TROUBLESHOOT_NOTFOUND {
            get {
                return ResourceManager.GetString("TROUBLESHOOT_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to USB drive: SUCCEEDED.
        /// </summary>
        internal static string TROUBLESHOOT_SUCCEEDED {
            get {
                return ResourceManager.GetString("TROUBLESHOOT_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No iNet activation.
        /// </summary>
        internal static string UNACTIVATED {
            get {
                return ResourceManager.GetString("UNACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 118.
        /// </summary>
        internal static string UNAVAILABLE {
            get {
                return ResourceManager.GetString("UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable Gas.
        /// </summary>
        internal static string UNAVAILABLEGAS {
            get {
                return ResourceManager.GetString("UNAVAILABLEGAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undocked Instrument.
        /// </summary>
        internal static string UNDOCKEDINSTRUMENT {
            get {
                return ResourceManager.GetString("UNDOCKEDINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered Instrument Contact Administrator.
        /// </summary>
        internal static string UNREGISTEREDINSTRUMENT {
            get {
                return ResourceManager.GetString("UNREGISTEREDINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 106.
        /// </summary>
        internal static string UNSERIALIZEDINSTRUMENT {
            get {
                return ResourceManager.GetString("UNSERIALIZEDINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Cylinder
        ///on Port 1.
        /// </summary>
        internal static string UNSUPPORTEDCYLINDER1 {
            get {
                return ResourceManager.GetString("UNSUPPORTEDCYLINDER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Cylinder
        ///on Port 2.
        /// </summary>
        internal static string UNSUPPORTEDCYLINDER2 {
            get {
                return ResourceManager.GetString("UNSUPPORTEDCYLINDER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Cylinder
        ///on Port 3.
        /// </summary>
        internal static string UNSUPPORTEDCYLINDER3 {
            get {
                return ResourceManager.GetString("UNSUPPORTEDCYLINDER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Instrument.
        /// </summary>
        internal static string UNSUPPORTEDINSTRUMENT {
            get {
                return ResourceManager.GetString("UNSUPPORTEDINSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Software Version.
        /// </summary>
        internal static string UNSUPPORTEDSOFTWARE {
            get {
                return ResourceManager.GetString("UNSUPPORTEDSOFTWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Settings.
        /// </summary>
        internal static string UPDATINGDATA {
            get {
                return ResourceManager.GetString("UPDATINGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Instrument Settings.
        /// </summary>
        internal static string UPDATINGINSTRUMENTDATA {
            get {
                return ResourceManager.GetString("UPDATINGINSTRUMENTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPGRADING FIRMWARE.
        /// </summary>
        internal static string UPGRADINGFIRMWARE {
            get {
                return ResourceManager.GetString("UPGRADINGFIRMWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ISC Code 109.
        /// </summary>
        internal static string UPGRADINGINSTRUMENTERROR {
            get {
                return ResourceManager.GetString("UPGRADINGINSTRUMENTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading Instrument
        ///DO NOT UNDOCK.
        /// </summary>
        internal static string UPGRADINGINSTRUMENTFIRMWARE {
            get {
                return ResourceManager.GetString("UPGRADINGINSTRUMENTFIRMWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Database.
        /// </summary>
        internal static string UPLOADINGDATABASE {
            get {
                return ResourceManager.GetString("UPLOADINGDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Debug Log.
        /// </summary>
        internal static string UPLOADINGDEBUGLOG {
            get {
                return ResourceManager.GetString("UPLOADINGDEBUGLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying.
        /// </summary>
        internal static string VERIFYING {
            get {
                return ResourceManager.GetString("VERIFYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string VERSION_ABBREV {
            get {
                return ResourceManager.GetString("VERSION_ABBREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Air.
        /// </summary>
        internal static string ZEROAIR {
            get {
                return ResourceManager.GetString("ZEROAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeroing.
        /// </summary>
        internal static string ZEROING {
            get {
                return ResourceManager.GetString("ZEROING", resourceCulture);
            }
        }
    }
}
