//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC.iNet.DS.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class CsvFileManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal CsvFileManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISC.iNet.DS.Services.Resources.CsvFileManagerResources", typeof(CsvFileManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Column_A_PeriodNumber {
            get {
                return ResourceManager.GetString("Column_A_PeriodNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Column_B_User {
            get {
                return ResourceManager.GetString("Column_B_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Column_C_Site {
            get {
                return ResourceManager.GetString("Column_C_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Column_D_ReadingTime {
            get {
                return ResourceManager.GetString("Column_D_ReadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp °C.
        /// </summary>
        internal static string Column_E_Temp {
            get {
                return ResourceManager.GetString("Column_E_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Column_F_SensorGasDetected {
            get {
                return ResourceManager.GetString("Column_F_SensorGasDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWA.
        /// </summary>
        internal static string Column_G_SensorTWA {
            get {
                return ResourceManager.GetString("Column_G_SensorTWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEL.
        /// </summary>
        internal static string Column_H_SensorSTEL {
            get {
                return ResourceManager.GetString("Column_H_SensorSTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BumpTests_.
        /// </summary>
        internal static string Filename_BumpTests_ {
            get {
                return ResourceManager.GetString("Filename_BumpTests_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrations_.
        /// </summary>
        internal static string Filename_Calibrations_ {
            get {
                return ResourceManager.GetString("Filename_Calibrations_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalog_.
        /// </summary>
        internal static string Filename_Datalog_ {
            get {
                return ResourceManager.GetString("Filename_Datalog_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string Text_NotApplicable {
            get {
                return ResourceManager.GetString("Text_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SESSION CORRUPTION DETECTED.
        /// </summary>
        internal static string Text_SessionCorruptionDetected {
            get {
                return ResourceManager.GetString("Text_SessionCorruptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDOCKED INSTRUMENT.
        /// </summary>
        internal static string Text_UndockedInstrument {
            get {
                return ResourceManager.GetString("Text_UndockedInstrument", resourceCulture);
            }
        }
    }
}
