//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC.iNet.DS.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISC.iNet.DS.Services.Resources.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach pump adapter..
        /// </summary>
        internal static string ATTACH_PUMP_ADAPTER {
            get {
                return ResourceManager.GetString("ATTACH_PUMP_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight is off..
        /// </summary>
        internal static string BACKLIGHT_IS_OFF {
            get {
                return ResourceManager.GetString("BACKLIGHT_IS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight is on..
        /// </summary>
        internal static string BACKLIGHT_IS_ON {
            get {
                return ResourceManager.GetString("BACKLIGHT_IS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery installed.
        /// </summary>
        internal static string BATTERY_INSTALLED {
            get {
                return ResourceManager.GetString("BATTERY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9v Disposable Battery.
        /// </summary>
        internal static string BP001 {
            get {
                return ResourceManager.GetString("BP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Battery Pack.
        /// </summary>
        internal static string BP002 {
            get {
                return ResourceManager.GetString("BP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Battery Pack.
        /// </summary>
        internal static string BP003 {
            get {
                return ResourceManager.GetString("BP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline Battery Pack.
        /// </summary>
        internal static string BP004 {
            get {
                return ResourceManager.GetString("BP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline Battery Pack.
        /// </summary>
        internal static string BP005 {
            get {
                return ResourceManager.GetString("BP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Cell Lithium Battery Pack.
        /// </summary>
        internal static string BP006 {
            get {
                return ResourceManager.GetString("BP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Cell Lithium Battery Pack.
        /// </summary>
        internal static string BP007 {
            get {
                return ResourceManager.GetString("BP007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline battery pack.
        /// </summary>
        internal static string BP008 {
            get {
                return ResourceManager.GetString("BP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP009 {
            get {
                return ResourceManager.GetString("BP009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP010 {
            get {
                return ResourceManager.GetString("BP010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP011 {
            get {
                return ResourceManager.GetString("BP011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP012 {
            get {
                return ResourceManager.GetString("BP012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP013 {
            get {
                return ResourceManager.GetString("BP013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP014 {
            get {
                return ResourceManager.GetString("BP014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP015 {
            get {
                return ResourceManager.GetString("BP015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP016 {
            get {
                return ResourceManager.GetString("BP016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer is off..
        /// </summary>
        internal static string BUZZER_IS_OFF {
            get {
                return ResourceManager.GetString("BUZZER_IS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer is on..
        /// </summary>
        internal static string BUZZER_IS_ON {
            get {
                return ResourceManager.GetString("BUZZER_IS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer works correctly.
        /// </summary>
        internal static string BUZZER_TEST {
            get {
                return ResourceManager.GetString("BUZZER_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did Buzzer work correctly?.
        /// </summary>
        internal static string BUZZER_TEST_PROMPT {
            get {
                return ResourceManager.GetString("BUZZER_TEST_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic LCD/Key function.
        /// </summary>
        internal static string CAN_YOU_SEE_THIS {
            get {
                return ResourceManager.GetString("CAN_YOU_SEE_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        internal static string CHARGING {
            get {
                return ResourceManager.GetString("CHARGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect iGas connectors..
        /// </summary>
        internal static string CONNECT_IGAS_CONNECTOR {
            get {
                return ResourceManager.GetString("CONNECT_IGAS_CONNECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Voltage.
        /// </summary>
        internal static string CORE_VOLTAGE {
            get {
                return ResourceManager.GetString("CORE_VOLTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cradle routes flow to lid.
        /// </summary>
        internal static string CRADLE_SOLENOID_LID {
            get {
                return ResourceManager.GetString("CRADLE_SOLENOID_LID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is air flowing through diffusion lid?.
        /// </summary>
        internal static string CRADLE_SOLENOID_LID_PROMPT {
            get {
                return ResourceManager.GetString("CRADLE_SOLENOID_LID_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cradle routes flow to hose.
        /// </summary>
        internal static string CRADLE_SOLENOID_PUMP {
            get {
                return ResourceManager.GetString("CRADLE_SOLENOID_PUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is air flowing through instrument hose?.
        /// </summary>
        internal static string CRADLE_SOLENOID_PUMP_PROMPT {
            get {
                return ResourceManager.GetString("CRADLE_SOLENOID_PUMP_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_HARDWARE_VERSION {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_HARDWARE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Station.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_HEADER {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_IP_ADDRESS {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_LANGUAGE {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_MAC_ADDRESS {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_MAC_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Lock.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_MENU_LOCKED {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_MENU_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Ports.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_NUM_GAS_PORTS {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_NUM_GAS_PORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_PART_NUMBER {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_PART_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Reservoir.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_RESERVOIR {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_RESERVOIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Diagnostics Date.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_SELF_DIAGNOSTICS_DATE {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_SELF_DIAGNOSTICS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_SERIALNUMBER {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_SERIALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Diagnostics Date.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_SERVICE_DIAGNOSTICS_DATE {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_SERVICE_DIAGNOSTICS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Date.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_SETUP_DATE {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_SETUP_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Technician.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_SETUP_TECH {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_SETUP_TECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_SOFTWARE_VERSION {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_SOFTWARE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_TYPE {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Audible Alarm.
        /// </summary>
        internal static string DETAILS_DOCKINGSTATION_USE_AUDIBLE_ALARM {
            get {
                return ResourceManager.GetString("DETAILS_DOCKINGSTATION_USE_AUDIBLE_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffusion lid lowered.
        /// </summary>
        internal static string DIFFUSION_LID_DETECT {
            get {
                return ResourceManager.GetString("DIFFUSION_LID_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect iGas connectors..
        /// </summary>
        internal static string DISCONNECT_IGAS_CONNECTOR {
            get {
                return ResourceManager.GetString("DISCONNECT_IGAS_CONNECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock an instrument..
        /// </summary>
        internal static string DOCK_INSTRUMENT {
            get {
                return ResourceManager.GetString("DOCK_INSTRUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ENGUS {
            get {
                return ResourceManager.GetString("ENGUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        internal static string FLOW {
            get {
                return ResourceManager.GetString("FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left increases voltage, right decreases voltage, middle accepts..
        /// </summary>
        internal static string FLOW_ADJUST {
            get {
                return ResourceManager.GetString("FLOW_ADJUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow:.
        /// </summary>
        internal static string FLOW_LABEL {
            get {
                return ResourceManager.GetString("FLOW_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Offset.
        /// </summary>
        internal static string FLOW_OFFSET {
            get {
                return ResourceManager.GetString("FLOW_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FRNFR {
            get {
                return ResourceManager.GetString("FRNFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Gas Port #).
        /// </summary>
        internal static string GAS_PORT {
            get {
                return ResourceManager.GetString("GAS_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasBadge Plus Single Gas Monitor.
        /// </summary>
        internal static string GBPLS {
            get {
                return ResourceManager.GetString("GBPLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasBadge Pro Single Gas Monitor.
        /// </summary>
        internal static string GBPRO {
            get {
                return ResourceManager.GetString("GBPRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string GRMGR {
            get {
                return ResourceManager.GetString("GRMGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery code.
        /// </summary>
        internal static string INSTRUMENT_BATTERY_CODE {
            get {
                return ResourceManager.GetString("INSTRUMENT_BATTERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this the correct battery?.
        /// </summary>
        internal static string INSTRUMENT_BATTERY_CODE_PROMPT {
            get {
                return ResourceManager.GetString("INSTRUMENT_BATTERY_CODE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument charging.
        /// </summary>
        internal static string INSTRUMENT_CHARGING {
            get {
                return ResourceManager.GetString("INSTRUMENT_CHARGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument present.
        /// </summary>
        internal static string INSTRUMENT_DETECT {
            get {
                return ResourceManager.GetString("INSTRUMENT_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument ping.
        /// </summary>
        internal static string INSTRUMENT_PING {
            get {
                return ResourceManager.GetString("INSTRUMENT_PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did LCD and backlight work correctly?.
        /// </summary>
        internal static string LCD_AND_BACKLIGHT_PROMPT {
            get {
                return ResourceManager.GetString("LCD_AND_BACKLIGHT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCD and backlight work correctly.
        /// </summary>
        internal static string LCD_AND_BACKLIGHT_TEST {
            get {
                return ResourceManager.GetString("LCD_AND_BACKLIGHT_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Check #1.
        /// </summary>
        internal static string LEAK_CHECK_1 {
            get {
                return ResourceManager.GetString("LEAK_CHECK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Check #2.
        /// </summary>
        internal static string LEAK_CHECK_2 {
            get {
                return ResourceManager.GetString("LEAK_CHECK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green LED is on..
        /// </summary>
        internal static string LED_GREEN_ON {
            get {
                return ResourceManager.GetString("LED_GREEN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did LEDs work correctly?.
        /// </summary>
        internal static string LED_PROMPT {
            get {
                return ResourceManager.GetString("LED_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red LED is on..
        /// </summary>
        internal static string LED_RED_ON {
            get {
                return ResourceManager.GetString("LED_RED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDs work correctly.
        /// </summary>
        internal static string LED_TEST {
            get {
                return ResourceManager.GetString("LED_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow LED is on..
        /// </summary>
        internal static string LED_YELLOW_ON {
            get {
                return ResourceManager.GetString("LED_YELLOW_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDs are off..
        /// </summary>
        internal static string LEDS_ALL_OFF {
            get {
                return ResourceManager.GetString("LEDS_ALL_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left key.
        /// </summary>
        internal static string LEFT {
            get {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low battery.
        /// </summary>
        internal static string LOWBATTERY {
            get {
                return ResourceManager.GetString("LOWBATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower diffusion lid..
        /// </summary>
        internal static string LOWER_DIFFUSION_LID {
            get {
                return ResourceManager.GetString("LOWER_DIFFUSION_LID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address Default.
        /// </summary>
        internal static string MAC_ADDRESS_DEFAULT {
            get {
                return ResourceManager.GetString("MAC_ADDRESS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address OUI.
        /// </summary>
        internal static string MAC_ADDRESS_OUI {
            get {
                return ResourceManager.GetString("MAC_ADDRESS_OUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle key.
        /// </summary>
        internal static string MIDDLE {
            get {
                return ResourceManager.GetString("MIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mA.
        /// </summary>
        internal static string MILLIAMPS {
            get {
                return ResourceManager.GetString("MILLIAMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mV.
        /// </summary>
        internal static string MILLIVOLTS {
            get {
                return ResourceManager.GetString("MILLIVOLTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml/min.
        /// </summary>
        internal static string MLMIN {
            get {
                return ResourceManager.GetString("MLMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX4 Ventis/iQuad Multi-Gas Monitor.
        /// </summary>
        internal static string MX4 {
            get {
                return ResourceManager.GetString("MX4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX6 iBrid Multi-Gas Monitor.
        /// </summary>
        internal static string MX6 {
            get {
                return ResourceManager.GetString("MX6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffusion lid raised.
        /// </summary>
        internal static string NO_DIFFUSION_LID_DETECT {
            get {
                return ResourceManager.GetString("NO_DIFFUSION_LID_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument absent.
        /// </summary>
        internal static string NO_INSTRUMENT_DETECT {
            get {
                return ResourceManager.GetString("NO_INSTRUMENT_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pressure switch #1.
        /// </summary>
        internal static string NO_PRESSURE_SWITCH_1 {
            get {
                return ResourceManager.GetString("NO_PRESSURE_SWITCH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pressure switch #2.
        /// </summary>
        internal static string NO_PRESSURE_SWITCH_2 {
            get {
                return ResourceManager.GetString("NO_PRESSURE_SWITCH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pressure switch #3.
        /// </summary>
        internal static string NO_PRESSURE_SWITCH_3 {
            get {
                return ResourceManager.GetString("NO_PRESSURE_SWITCH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pressure switch #4.
        /// </summary>
        internal static string NO_PRESSURE_SWITCH_4 {
            get {
                return ResourceManager.GetString("NO_PRESSURE_SWITCH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pressure switch #5.
        /// </summary>
        internal static string NO_PRESSURE_SWITCH_5 {
            get {
                return ResourceManager.GetString("NO_PRESSURE_SWITCH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pressure switch #6.
        /// </summary>
        internal static string NO_PRESSURE_SWITCH_6 {
            get {
                return ResourceManager.GetString("NO_PRESSURE_SWITCH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump adapter absent.
        /// </summary>
        internal static string NO_PUMP_ADAPTER_DETECT {
            get {
                return ResourceManager.GetString("NO_PUMP_ADAPTER_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card #1.
        /// </summary>
        internal static string NO_SMART_CARD_1 {
            get {
                return ResourceManager.GetString("NO_SMART_CARD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card #2.
        /// </summary>
        internal static string NO_SMART_CARD_2 {
            get {
                return ResourceManager.GetString("NO_SMART_CARD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card #3.
        /// </summary>
        internal static string NO_SMART_CARD_3 {
            get {
                return ResourceManager.GetString("NO_SMART_CARD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card #4.
        /// </summary>
        internal static string NO_SMART_CARD_4 {
            get {
                return ResourceManager.GetString("NO_SMART_CARD_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card #5.
        /// </summary>
        internal static string NO_SMART_CARD_5 {
            get {
                return ResourceManager.GetString("NO_SMART_CARD_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smart card #6.
        /// </summary>
        internal static string NO_SMART_CARD_6 {
            get {
                return ResourceManager.GetString("NO_SMART_CARD_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NOT_APPLICABLE {
            get {
                return ResourceManager.GetString("NOT_APPLICABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not charging.
        /// </summary>
        internal static string NOTCHARGING {
            get {
                return ResourceManager.GetString("NOTCHARGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there # gas ports?.
        /// </summary>
        internal static string NUM_GAS_PORTS_PROMPT {
            get {
                return ResourceManager.GetString("NUM_GAS_PORTS_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of gas ports.
        /// </summary>
        internal static string NUM_GAS_PORTS_TEST {
            get {
                return ResourceManager.GetString("NUM_GAS_PORTS_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        internal static string OFFSET_LABEL {
            get {
                return ResourceManager.GetString("OFFSET_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string PASSED {
            get {
                return ResourceManager.GetString("PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key?.
        /// </summary>
        internal static string PRESS_ANY_KEY_PROMPT {
            get {
                return ResourceManager.GetString("PRESS_ANY_KEY_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue..
        /// </summary>
        internal static string PRESS_ANY_TO_CONTINUE {
            get {
                return ResourceManager.GetString("PRESS_ANY_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to start pump..
        /// </summary>
        internal static string PRESS_ANY_TO_START_PUMP {
            get {
                return ResourceManager.GetString("PRESS_ANY_TO_START_PUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left key press.
        /// </summary>
        internal static string PRESS_KEY_LEFT {
            get {
                return ResourceManager.GetString("PRESS_KEY_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the left key.
        /// </summary>
        internal static string PRESS_KEY_LEFT_PROMPT {
            get {
                return ResourceManager.GetString("PRESS_KEY_LEFT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle key press.
        /// </summary>
        internal static string PRESS_KEY_MIDDLE {
            get {
                return ResourceManager.GetString("PRESS_KEY_MIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the middle key.
        /// </summary>
        internal static string PRESS_KEY_MIDDLE_PROMPT {
            get {
                return ResourceManager.GetString("PRESS_KEY_MIDDLE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right key press.
        /// </summary>
        internal static string PRESS_KEY_RIGHT {
            get {
                return ResourceManager.GetString("PRESS_KEY_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the right key.
        /// </summary>
        internal static string PRESS_KEY_RIGHT_PROMPT {
            get {
                return ResourceManager.GetString("PRESS_KEY_RIGHT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left pass, right fail.
        /// </summary>
        internal static string PRESS_LEFT_SUCCESS_PROMPT {
            get {
                return ResourceManager.GetString("PRESS_LEFT_SUCCESS_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #1 present.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESENT_1 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #2 present.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESENT_2 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #3 present.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESENT_3 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESENT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #4 present.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESENT_4 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESENT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #5 present.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESENT_5 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESENT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #6 present.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESENT_6 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESENT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #1 pressure.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESSURE_1 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESSURE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #2 pressure.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESSURE_2 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESSURE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #3 pressure.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESSURE_3 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESSURE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #4 pressure.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESSURE_4 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESSURE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #5 pressure.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESSURE_5 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESSURE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure switch #6 pressure.
        /// </summary>
        internal static string PRESSURE_SWITCH_PRESSURE_6 {
            get {
                return ResourceManager.GetString("PRESSURE_SWITCH_PRESSURE_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string PRTBR {
            get {
                return ResourceManager.GetString("PRTBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump.
        /// </summary>
        internal static string PUMP {
            get {
                return ResourceManager.GetString("PUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump adapter present.
        /// </summary>
        internal static string PUMP_ADAPTER_DETECT {
            get {
                return ResourceManager.GetString("PUMP_ADAPTER_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump Error Status.
        /// </summary>
        internal static string PUMP_ERROR_STATUS {
            get {
                return ResourceManager.GetString("PUMP_ERROR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise diffusion lid..
        /// </summary>
        internal static string RAISE_DIFFUSION_LID {
            get {
                return ResourceManager.GetString("RAISE_DIFFUSION_LID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove pump adapter..
        /// </summary>
        internal static string REMOVE_PUMP_ADAPTER {
            get {
                return ResourceManager.GetString("REMOVE_PUMP_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right key.
        /// </summary>
        internal static string RIGHT {
            get {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart card #1 present.
        /// </summary>
        internal static string SMART_CARD_PRESENT_1 {
            get {
                return ResourceManager.GetString("SMART_CARD_PRESENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart card #2 present.
        /// </summary>
        internal static string SMART_CARD_PRESENT_2 {
            get {
                return ResourceManager.GetString("SMART_CARD_PRESENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart card #3 present.
        /// </summary>
        internal static string SMART_CARD_PRESENT_3 {
            get {
                return ResourceManager.GetString("SMART_CARD_PRESENT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart card #4 present.
        /// </summary>
        internal static string SMART_CARD_PRESENT_4 {
            get {
                return ResourceManager.GetString("SMART_CARD_PRESENT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart card #5 present.
        /// </summary>
        internal static string SMART_CARD_PRESENT_5 {
            get {
                return ResourceManager.GetString("SMART_CARD_PRESENT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart card #6 present.
        /// </summary>
        internal static string SMART_CARD_PRESENT_6 {
            get {
                return ResourceManager.GetString("SMART_CARD_PRESENT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #1 Current.
        /// </summary>
        internal static string SOLENOID_CURRENT_1 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #2 Current.
        /// </summary>
        internal static string SOLENOID_CURRENT_2 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #3 Current.
        /// </summary>
        internal static string SOLENOID_CURRENT_3 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #4 Current.
        /// </summary>
        internal static string SOLENOID_CURRENT_4 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #5 Current.
        /// </summary>
        internal static string SOLENOID_CURRENT_5 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #6 Current.
        /// </summary>
        internal static string SOLENOID_CURRENT_6 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #1 Flow.
        /// </summary>
        internal static string SOLENOID_FLOW_1 {
            get {
                return ResourceManager.GetString("SOLENOID_FLOW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #2 Flow.
        /// </summary>
        internal static string SOLENOID_FLOW_2 {
            get {
                return ResourceManager.GetString("SOLENOID_FLOW_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #3 Flow.
        /// </summary>
        internal static string SOLENOID_FLOW_3 {
            get {
                return ResourceManager.GetString("SOLENOID_FLOW_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #4 Flow.
        /// </summary>
        internal static string SOLENOID_FLOW_4 {
            get {
                return ResourceManager.GetString("SOLENOID_FLOW_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #5 Flow.
        /// </summary>
        internal static string SOLENOID_FLOW_5 {
            get {
                return ResourceManager.GetString("SOLENOID_FLOW_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #6 Flow.
        /// </summary>
        internal static string SOLENOID_FLOW_6 {
            get {
                return ResourceManager.GetString("SOLENOID_FLOW_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #1 No Flow.
        /// </summary>
        internal static string SOLENOID_NO_FLOW_1 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_FLOW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #2 No Flow.
        /// </summary>
        internal static string SOLENOID_NO_FLOW_2 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_FLOW_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #3 No Flow.
        /// </summary>
        internal static string SOLENOID_NO_FLOW_3 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_FLOW_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #4 No Flow.
        /// </summary>
        internal static string SOLENOID_NO_FLOW_4 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_FLOW_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #5 No Flow.
        /// </summary>
        internal static string SOLENOID_NO_FLOW_5 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_FLOW_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #6 No Flow.
        /// </summary>
        internal static string SOLENOID_NO_FLOW_6 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_FLOW_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #1 No Vacuum.
        /// </summary>
        internal static string SOLENOID_NO_VACUUM_1 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_VACUUM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #2 No Vacuum.
        /// </summary>
        internal static string SOLENOID_NO_VACUUM_2 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_VACUUM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #3 No Vacuum.
        /// </summary>
        internal static string SOLENOID_NO_VACUUM_3 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_VACUUM_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #4 No Vacuum.
        /// </summary>
        internal static string SOLENOID_NO_VACUUM_4 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_VACUUM_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #5 No Vacuum.
        /// </summary>
        internal static string SOLENOID_NO_VACUUM_5 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_VACUUM_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #6 No Vacuum.
        /// </summary>
        internal static string SOLENOID_NO_VACUUM_6 {
            get {
                return ResourceManager.GetString("SOLENOID_NO_VACUUM_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #1 Pump Error.
        /// </summary>
        internal static string SOLENOID_PUMP_ERROR_1 {
            get {
                return ResourceManager.GetString("SOLENOID_PUMP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #2 Pump Error.
        /// </summary>
        internal static string SOLENOID_PUMP_ERROR_2 {
            get {
                return ResourceManager.GetString("SOLENOID_PUMP_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #3 Pump Error.
        /// </summary>
        internal static string SOLENOID_PUMP_ERROR_3 {
            get {
                return ResourceManager.GetString("SOLENOID_PUMP_ERROR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #4 Pump Error.
        /// </summary>
        internal static string SOLENOID_PUMP_ERROR_4 {
            get {
                return ResourceManager.GetString("SOLENOID_PUMP_ERROR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #5 Pump Error.
        /// </summary>
        internal static string SOLENOID_PUMP_ERROR_5 {
            get {
                return ResourceManager.GetString("SOLENOID_PUMP_ERROR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #6 Pump Error.
        /// </summary>
        internal static string SOLENOID_PUMP_ERROR_6 {
            get {
                return ResourceManager.GetString("SOLENOID_PUMP_ERROR_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #1 Vacuum.
        /// </summary>
        internal static string SOLENOID_VACUUM_1 {
            get {
                return ResourceManager.GetString("SOLENOID_VACUUM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #2 Vacuum.
        /// </summary>
        internal static string SOLENOID_VACUUM_2 {
            get {
                return ResourceManager.GetString("SOLENOID_VACUUM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #3 Vacuum.
        /// </summary>
        internal static string SOLENOID_VACUUM_3 {
            get {
                return ResourceManager.GetString("SOLENOID_VACUUM_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #4 Vacuum.
        /// </summary>
        internal static string SOLENOID_VACUUM_4 {
            get {
                return ResourceManager.GetString("SOLENOID_VACUUM_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #5 Vacuum.
        /// </summary>
        internal static string SOLENOID_VACUUM_5 {
            get {
                return ResourceManager.GetString("SOLENOID_VACUUM_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid #6 Vacuum.
        /// </summary>
        internal static string SOLENOID_VACUUM_6 {
            get {
                return ResourceManager.GetString("SOLENOID_VACUUM_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string SPNSP {
            get {
                return ResourceManager.GetString("SPNSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Current.
        /// </summary>
        internal static string SYSTEM_CURRENT {
            get {
                return ResourceManager.GetString("SYSTEM_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top off.
        /// </summary>
        internal static string TOPOFF {
            get {
                return ResourceManager.GetString("TOPOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cradle flow through hose.
        /// </summary>
        internal static string TUBING_ADAPTER_FLOW {
            get {
                return ResourceManager.GetString("TUBING_ADAPTER_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there flow through the adapter?.
        /// </summary>
        internal static string TUBING_ADAPTER_FLOW_PROMPT {
            get {
                return ResourceManager.GetString("TUBING_ADAPTER_FLOW_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect tubing adapter.
        /// </summary>
        internal static string TUBING_ADAPTER_PROMPT {
            get {
                return ResourceManager.GetString("TUBING_ADAPTER_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum.
        /// </summary>
        internal static string VACUUM {
            get {
                return ResourceManager.GetString("VACUUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum Error Status.
        /// </summary>
        internal static string VACUUM_ERROR_STATUS {
            get {
                return ResourceManager.GetString("VACUUM_ERROR_STATUS", resourceCulture);
            }
        }
    }
}
