//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC.iNet.DS.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class PrintManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal PrintManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISC.iNet.DS.Services.Resources.PrintManagerResources", typeof(PrintManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9v Disposable Battery.
        /// </summary>
        internal static string BP001 {
            get {
                return ResourceManager.GetString("BP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Battery Pack.
        /// </summary>
        internal static string BP002 {
            get {
                return ResourceManager.GetString("BP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium Battery Pack.
        /// </summary>
        internal static string BP003 {
            get {
                return ResourceManager.GetString("BP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline Battery Pack.
        /// </summary>
        internal static string BP004 {
            get {
                return ResourceManager.GetString("BP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline Battery Pack.
        /// </summary>
        internal static string BP005 {
            get {
                return ResourceManager.GetString("BP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Cell Lithium Battery Pack.
        /// </summary>
        internal static string BP006 {
            get {
                return ResourceManager.GetString("BP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Cell Lithium Battery Pack.
        /// </summary>
        internal static string BP007 {
            get {
                return ResourceManager.GetString("BP007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkaline battery pack.
        /// </summary>
        internal static string BP008 {
            get {
                return ResourceManager.GetString("BP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP009 {
            get {
                return ResourceManager.GetString("BP009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP010 {
            get {
                return ResourceManager.GetString("BP010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP011 {
            get {
                return ResourceManager.GetString("BP011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium-ion battery pack.
        /// </summary>
        internal static string BP012 {
            get {
                return ResourceManager.GetString("BP012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP013 {
            get {
                return ResourceManager.GetString("BP013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP014 {
            get {
                return ResourceManager.GetString("BP014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP015 {
            get {
                return ResourceManager.GetString("BP015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-cell lithium-ion battery pack.
        /// </summary>
        internal static string BP016 {
            get {
                return ResourceManager.GetString("BP016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm High.
        /// </summary>
        internal static string Column_AlarmHigh {
            get {
                return ResourceManager.GetString("Column_AlarmHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Low.
        /// </summary>
        internal static string Column_AlarmLow {
            get {
                return ResourceManager.GetString("Column_AlarmLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm STEL.
        /// </summary>
        internal static string Column_AlarmSTEL {
            get {
                return ResourceManager.GetString("Column_AlarmSTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm TWA.
        /// </summary>
        internal static string Column_AlarmTWA {
            get {
                return ResourceManager.GetString("Column_AlarmTWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Date/Time.
        /// </summary>
        internal static string Column_BumpDateTime {
            get {
                return ResourceManager.GetString("Column_BumpDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal Date/Time.
        /// </summary>
        internal static string Column_CalDateTime {
            get {
                return ResourceManager.GetString("Column_CalDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder Exp.
        /// </summary>
        internal static string Column_CylinderExp {
            get {
                return ResourceManager.GetString("Column_CylinderExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder ID.
        /// </summary>
        internal static string Column_CylinderID {
            get {
                return ResourceManager.GetString("Column_CylinderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string Column_Factor {
            get {
                return ResourceManager.GetString("Column_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Type.
        /// </summary>
        internal static string Column_GasType {
            get {
                return ResourceManager.GetString("Column_GasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed/Failed.
        /// </summary>
        internal static string Column_PassedFailed {
            get {
                return ResourceManager.GetString("Column_PassedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Reading.
        /// </summary>
        internal static string Column_SensorReading {
            get {
                return ResourceManager.GetString("Column_SensorReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor SN.
        /// </summary>
        internal static string Column_SensorSN {
            get {
                return ResourceManager.GetString("Column_SensorSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Type.
        /// </summary>
        internal static string Column_SensorType {
            get {
                return ResourceManager.GetString("Column_SensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span Gas.
        /// </summary>
        internal static string Column_SpanGas {
            get {
                return ResourceManager.GetString("Column_SpanGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span Reserve.
        /// </summary>
        internal static string Column_SpanReserve {
            get {
                return ResourceManager.GetString("Column_SpanReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Cylinder Exp.
        /// </summary>
        internal static string Column_ZeroCylinderExp {
            get {
                return ResourceManager.GetString("Column_ZeroCylinderExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Cylinder ID.
        /// </summary>
        internal static string Column_ZeroCylinderID {
            get {
                return ResourceManager.GetString("Column_ZeroCylinderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRESHAIR.
        /// </summary>
        internal static string FRESHAIR {
            get {
                return ResourceManager.GetString("FRESHAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon Monoxide.
        /// </summary>
        internal static string G0001 {
            get {
                return ResourceManager.GetString("G0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Sulfide.
        /// </summary>
        internal static string G0002 {
            get {
                return ResourceManager.GetString("G0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfur Dioxide.
        /// </summary>
        internal static string G0003 {
            get {
                return ResourceManager.GetString("G0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen Dioxide.
        /// </summary>
        internal static string G0004 {
            get {
                return ResourceManager.GetString("G0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine.
        /// </summary>
        internal static string G0005 {
            get {
                return ResourceManager.GetString("G0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine Dioxide.
        /// </summary>
        internal static string G0006 {
            get {
                return ResourceManager.GetString("G0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Cyanide.
        /// </summary>
        internal static string G0007 {
            get {
                return ResourceManager.GetString("G0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphine.
        /// </summary>
        internal static string G0008 {
            get {
                return ResourceManager.GetString("G0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen.
        /// </summary>
        internal static string G0009 {
            get {
                return ResourceManager.GetString("G0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon Dioxide.
        /// </summary>
        internal static string G0011 {
            get {
                return ResourceManager.GetString("G0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitric Oxide.
        /// </summary>
        internal static string G0012 {
            get {
                return ResourceManager.GetString("G0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia.
        /// </summary>
        internal static string G0013 {
            get {
                return ResourceManager.GetString("G0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Chloride.
        /// </summary>
        internal static string G0014 {
            get {
                return ResourceManager.GetString("G0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozone.
        /// </summary>
        internal static string G0015 {
            get {
                return ResourceManager.GetString("G0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosgene.
        /// </summary>
        internal static string G0016 {
            get {
                return ResourceManager.GetString("G0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Flouride.
        /// </summary>
        internal static string G0017 {
            get {
                return ResourceManager.GetString("G0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR-Methane.
        /// </summary>
        internal static string G0018 {
            get {
                return ResourceManager.GetString("G0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustible PPM.
        /// </summary>
        internal static string G0019 {
            get {
                return ResourceManager.GetString("G0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen.
        /// </summary>
        internal static string G0020 {
            get {
                return ResourceManager.GetString("G0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methane.
        /// </summary>
        internal static string G0021 {
            get {
                return ResourceManager.GetString("G0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustible LEL.
        /// </summary>
        internal static string G0022 {
            get {
                return ResourceManager.GetString("G0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexane.
        /// </summary>
        internal static string G0023 {
            get {
                return ResourceManager.GetString("G0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentane.
        /// </summary>
        internal static string G0026 {
            get {
                return ResourceManager.GetString("G0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propane.
        /// </summary>
        internal static string G0027 {
            get {
                return ResourceManager.GetString("G0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butanediol,1,4-.
        /// </summary>
        internal static string G0028 {
            get {
                return ResourceManager.GetString("G0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dioxane,1,4-.
        /// </summary>
        internal static string G0029 {
            get {
                return ResourceManager.GetString("G0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimethyl Benzene,1,2,4-.
        /// </summary>
        internal static string G0030 {
            get {
                return ResourceManager.GetString("G0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimethyl Benzene,1,2,3-.
        /// </summary>
        internal static string G0031 {
            get {
                return ResourceManager.GetString("G0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dibromoethane,1,2-.
        /// </summary>
        internal static string G0032 {
            get {
                return ResourceManager.GetString("G0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichlorobenzene,1,2-.
        /// </summary>
        internal static string G0033 {
            get {
                return ResourceManager.GetString("G0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimethylbenzene,1,3,5-.
        /// </summary>
        internal static string G0034 {
            get {
                return ResourceManager.GetString("G0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butanol,1-.
        /// </summary>
        internal static string G0035 {
            get {
                return ResourceManager.GetString("G0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methoxypropanol.
        /// </summary>
        internal static string G0036 {
            get {
                return ResourceManager.GetString("G0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propanol,1-.
        /// </summary>
        internal static string G0037 {
            get {
                return ResourceManager.GetString("G0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Acetate.
        /// </summary>
        internal static string G0038 {
            get {
                return ResourceManager.GetString("G0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Acrylate.
        /// </summary>
        internal static string G0039 {
            get {
                return ResourceManager.GetString("G0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Acetoacetate.
        /// </summary>
        internal static string G0040 {
            get {
                return ResourceManager.GetString("G0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Benzoate.
        /// </summary>
        internal static string G0041 {
            get {
                return ResourceManager.GetString("G0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Methacrylate.
        /// </summary>
        internal static string G0042 {
            get {
                return ResourceManager.GetString("G0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butanone,2-.
        /// </summary>
        internal static string G0043 {
            get {
                return ResourceManager.GetString("G0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Formamide,1-.
        /// </summary>
        internal static string G0044 {
            get {
                return ResourceManager.GetString("G0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methoxy Ethanol.
        /// </summary>
        internal static string G0045 {
            get {
                return ResourceManager.GetString("G0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentanone,2-.
        /// </summary>
        internal static string G0046 {
            get {
                return ResourceManager.GetString("G0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picoline,2-.
        /// </summary>
        internal static string G0047 {
            get {
                return ResourceManager.GetString("G0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propanol,2-.
        /// </summary>
        internal static string G0048 {
            get {
                return ResourceManager.GetString("G0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimethylformamide.
        /// </summary>
        internal static string G0049 {
            get {
                return ResourceManager.GetString("G0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimethyl Acetamide.
        /// </summary>
        internal static string G0050 {
            get {
                return ResourceManager.GetString("G0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picoline,3-.
        /// </summary>
        internal static string G0051 {
            get {
                return ResourceManager.GetString("G0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diacetone Alcohol.
        /// </summary>
        internal static string G0052 {
            get {
                return ResourceManager.GetString("G0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaldehyde.
        /// </summary>
        internal static string G0053 {
            get {
                return ResourceManager.GetString("G0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetone.
        /// </summary>
        internal static string G0054 {
            get {
                return ResourceManager.GetString("G0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetophenone.
        /// </summary>
        internal static string G0055 {
            get {
                return ResourceManager.GetString("G0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allyl Alcohol.
        /// </summary>
        internal static string G0056 {
            get {
                return ResourceManager.GetString("G0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia.
        /// </summary>
        internal static string G0057 {
            get {
                return ResourceManager.GetString("G0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amyl Acetate.
        /// </summary>
        internal static string G0058 {
            get {
                return ResourceManager.GetString("G0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzene.
        /// </summary>
        internal static string G0059 {
            get {
                return ResourceManager.GetString("G0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl Bromide.
        /// </summary>
        internal static string G0060 {
            get {
                return ResourceManager.GetString("G0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butadiene.
        /// </summary>
        internal static string G0061 {
            get {
                return ResourceManager.GetString("G0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butoxy Ethanol.
        /// </summary>
        internal static string G0062 {
            get {
                return ResourceManager.GetString("G0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butyl Acetate.
        /// </summary>
        internal static string G0063 {
            get {
                return ResourceManager.GetString("G0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetrachloroethylene.
        /// </summary>
        internal static string G0064 {
            get {
                return ResourceManager.GetString("G0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichloroethane,1,1-.
        /// </summary>
        internal static string G0065 {
            get {
                return ResourceManager.GetString("G0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethyl Benzene.
        /// </summary>
        internal static string G0066 {
            get {
                return ResourceManager.GetString("G0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trichloroethylene.
        /// </summary>
        internal static string G0067 {
            get {
                return ResourceManager.GetString("G0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethyl Acetoacetate.
        /// </summary>
        internal static string G0068 {
            get {
                return ResourceManager.GetString("G0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorobenzene.
        /// </summary>
        internal static string G0069 {
            get {
                return ResourceManager.GetString("G0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumene.
        /// </summary>
        internal static string G0070 {
            get {
                return ResourceManager.GetString("G0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylclohexane.
        /// </summary>
        internal static string G0071 {
            get {
                return ResourceManager.GetString("G0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclohexanone.
        /// </summary>
        internal static string G0072 {
            get {
                return ResourceManager.GetString("G0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decane.
        /// </summary>
        internal static string G0073 {
            get {
                return ResourceManager.GetString("G0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diethylamine.
        /// </summary>
        internal static string G0074 {
            get {
                return ResourceManager.GetString("G0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimethoxymethane.
        /// </summary>
        internal static string G0075 {
            get {
                return ResourceManager.GetString("G0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epichlorohydrin.
        /// </summary>
        internal static string G0076 {
            get {
                return ResourceManager.GetString("G0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethanol.
        /// </summary>
        internal static string G0077 {
            get {
                return ResourceManager.GetString("G0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethylene Glycol.
        /// </summary>
        internal static string G0078 {
            get {
                return ResourceManager.GetString("G0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethyl Acetate.
        /// </summary>
        internal static string G0079 {
            get {
                return ResourceManager.GetString("G0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethylene.
        /// </summary>
        internal static string G0080 {
            get {
                return ResourceManager.GetString("G0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethylene Oxide.
        /// </summary>
        internal static string G0081 {
            get {
                return ResourceManager.GetString("G0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butyrolactone.
        /// </summary>
        internal static string G0082 {
            get {
                return ResourceManager.GetString("G0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Sulfide.
        /// </summary>
        internal static string G0083 {
            get {
                return ResourceManager.GetString("G0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heptane.
        /// </summary>
        internal static string G0084 {
            get {
                return ResourceManager.GetString("G0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexane.
        /// </summary>
        internal static string G0085 {
            get {
                return ResourceManager.GetString("G0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrazine.
        /// </summary>
        internal static string G0086 {
            get {
                return ResourceManager.GetString("G0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isoamyl Acetate.
        /// </summary>
        internal static string G0087 {
            get {
                return ResourceManager.GetString("G0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isopropylamine.
        /// </summary>
        internal static string G0088 {
            get {
                return ResourceManager.GetString("G0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isopropyl Ether.
        /// </summary>
        internal static string G0089 {
            get {
                return ResourceManager.GetString("G0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isobutanol.
        /// </summary>
        internal static string G0090 {
            get {
                return ResourceManager.GetString("G0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isobutylene.
        /// </summary>
        internal static string G0091 {
            get {
                return ResourceManager.GetString("G0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isooctane.
        /// </summary>
        internal static string G0092 {
            get {
                return ResourceManager.GetString("G0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isophorone.
        /// </summary>
        internal static string G0093 {
            get {
                return ResourceManager.GetString("G0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isopropanol.
        /// </summary>
        internal static string G0094 {
            get {
                return ResourceManager.GetString("G0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet A Fuel.
        /// </summary>
        internal static string G0095 {
            get {
                return ResourceManager.GetString("G0095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet A1 Fuel.
        /// </summary>
        internal static string G0096 {
            get {
                return ResourceManager.GetString("G0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP-5 &amp; JP-8 Fuel.
        /// </summary>
        internal static string G0097 {
            get {
                return ResourceManager.GetString("G0097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEK (Methylethyl Ketone).
        /// </summary>
        internal static string G0098 {
            get {
                return ResourceManager.GetString("G0098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesityl Oxide.
        /// </summary>
        internal static string G0099 {
            get {
                return ResourceManager.GetString("G0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIBK (Methyl-Isobutyl Ketone).
        /// </summary>
        internal static string G0100 {
            get {
                return ResourceManager.GetString("G0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monomethylamine.
        /// </summary>
        internal static string G0101 {
            get {
                return ResourceManager.GetString("G0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTBE (Methyl-tertbutyl Ether).
        /// </summary>
        internal static string G0102 {
            get {
                return ResourceManager.GetString("G0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methylbenzyl alcohol.
        /// </summary>
        internal static string G0103 {
            get {
                return ResourceManager.GetString("G0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xylene,m-.
        /// </summary>
        internal static string G0104 {
            get {
                return ResourceManager.GetString("G0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methylpyrrolidone,n-.
        /// </summary>
        internal static string G0105 {
            get {
                return ResourceManager.GetString("G0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octane.
        /// </summary>
        internal static string G0106 {
            get {
                return ResourceManager.GetString("G0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xylene,o-.
        /// </summary>
        internal static string G0107 {
            get {
                return ResourceManager.GetString("G0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenelethyl Alcohol.
        /// </summary>
        internal static string G0108 {
            get {
                return ResourceManager.GetString("G0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenol.
        /// </summary>
        internal static string G0109 {
            get {
                return ResourceManager.GetString("G0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphine.
        /// </summary>
        internal static string G0110 {
            get {
                return ResourceManager.GetString("G0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propylene.
        /// </summary>
        internal static string G0111 {
            get {
                return ResourceManager.GetString("G0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propylene Oxide.
        /// </summary>
        internal static string G0112 {
            get {
                return ResourceManager.GetString("G0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xylene,p-.
        /// </summary>
        internal static string G0113 {
            get {
                return ResourceManager.GetString("G0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pryridine.
        /// </summary>
        internal static string G0114 {
            get {
                return ResourceManager.GetString("G0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinoline.
        /// </summary>
        internal static string G0115 {
            get {
                return ResourceManager.GetString("G0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styrene.
        /// </summary>
        internal static string G0116 {
            get {
                return ResourceManager.GetString("G0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tert-Butylamine.
        /// </summary>
        internal static string G0117 {
            get {
                return ResourceManager.GetString("G0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichloroethene,t-1,2-.
        /// </summary>
        internal static string G0118 {
            get {
                return ResourceManager.GetString("G0118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tert-Butyl Mercaptan.
        /// </summary>
        internal static string G0119 {
            get {
                return ResourceManager.GetString("G0119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tert-Butyl Alcohol.
        /// </summary>
        internal static string G0120 {
            get {
                return ResourceManager.GetString("G0120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THF (Tetrahydrofuran).
        /// </summary>
        internal static string G0121 {
            get {
                return ResourceManager.GetString("G0121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiophene.
        /// </summary>
        internal static string G0122 {
            get {
                return ResourceManager.GetString("G0122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toluene.
        /// </summary>
        internal static string G0123 {
            get {
                return ResourceManager.GetString("G0123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turpentine.
        /// </summary>
        internal static string G0124 {
            get {
                return ResourceManager.GetString("G0124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinylcylclohexene.
        /// </summary>
        internal static string G0125 {
            get {
                return ResourceManager.GetString("G0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinyl Acetate.
        /// </summary>
        internal static string G0126 {
            get {
                return ResourceManager.GetString("G0126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinyl Chloride.
        /// </summary>
        internal static string G0127 {
            get {
                return ResourceManager.GetString("G0127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzene Tube.
        /// </summary>
        internal static string G0128 {
            get {
                return ResourceManager.GetString("G0128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen.
        /// </summary>
        internal static string G0130 {
            get {
                return ResourceManager.GetString("G0130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butadiene.
        /// </summary>
        internal static string G0132 {
            get {
                return ResourceManager.GetString("G0132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isobutane.
        /// </summary>
        internal static string G0133 {
            get {
                return ResourceManager.GetString("G0133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetylene.
        /// </summary>
        internal static string G0200 {
            get {
                return ResourceManager.GetString("G0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butane.
        /// </summary>
        internal static string G0201 {
            get {
                return ResourceManager.GetString("G0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethane.
        /// </summary>
        internal static string G0202 {
            get {
                return ResourceManager.GetString("G0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methanol .
        /// </summary>
        internal static string G0203 {
            get {
                return ResourceManager.GetString("G0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP-4 Fuel.
        /// </summary>
        internal static string G0205 {
            get {
                return ResourceManager.GetString("G0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP-5 Fuel.
        /// </summary>
        internal static string G0206 {
            get {
                return ResourceManager.GetString("G0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP-8 Fuel.
        /// </summary>
        internal static string G0207 {
            get {
                return ResourceManager.GetString("G0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetic acid.
        /// </summary>
        internal static string G0208 {
            get {
                return ResourceManager.GetString("G0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetic Anhydride.
        /// </summary>
        internal static string G0209 {
            get {
                return ResourceManager.GetString("G0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsine.
        /// </summary>
        internal static string G0210 {
            get {
                return ResourceManager.GetString("G0210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bromine.
        /// </summary>
        internal static string G0211 {
            get {
                return ResourceManager.GetString("G0211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon disulfide.
        /// </summary>
        internal static string G0212 {
            get {
                return ResourceManager.GetString("G0212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclohexene.
        /// </summary>
        internal static string G0213 {
            get {
                return ResourceManager.GetString("G0213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel fuel.
        /// </summary>
        internal static string G0214 {
            get {
                return ResourceManager.GetString("G0214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimethyl sulfoxide.
        /// </summary>
        internal static string G0215 {
            get {
                return ResourceManager.GetString("G0215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethyl ether.
        /// </summary>
        internal static string G0216 {
            get {
                return ResourceManager.GetString("G0216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iodine.
        /// </summary>
        internal static string G0217 {
            get {
                return ResourceManager.GetString("G0217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methyl mercaptan.
        /// </summary>
        internal static string G0218 {
            get {
                return ResourceManager.GetString("G0218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naphthalene.
        /// </summary>
        internal static string G0219 {
            get {
                return ResourceManager.GetString("G0219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrobenzene.
        /// </summary>
        internal static string G0220 {
            get {
                return ResourceManager.GetString("G0220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methoxyethoxyethanol,2-.
        /// </summary>
        internal static string G0221 {
            get {
                return ResourceManager.GetString("G0221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonane.
        /// </summary>
        internal static string G0222 {
            get {
                return ResourceManager.GetString("G0222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrocarbon.
        /// </summary>
        internal static string G0248 {
            get {
                return ResourceManager.GetString("G0248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Air.
        /// </summary>
        internal static string G9999 {
            get {
                return ResourceManager.GetString("G9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery:.
        /// </summary>
        internal static string Label_Battery {
            get {
                return ResourceManager.GetString("Label_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Date:.
        /// </summary>
        internal static string Label_BumpDate {
            get {
                return ResourceManager.GetString("Label_BumpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Threshold:.
        /// </summary>
        internal static string Label_BumpThreshold {
            get {
                return ResourceManager.GetString("Label_BumpThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Timeout:.
        /// </summary>
        internal static string Label_BumpTimeout {
            get {
                return ResourceManager.GetString("Label_BumpTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Date:.
        /// </summary>
        internal static string Label_CalibrationDate {
            get {
                return ResourceManager.GetString("Label_CalibrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By:.
        /// </summary>
        internal static string Label_CreatedBy {
            get {
                return ResourceManager.GetString("Label_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument SN:.
        /// </summary>
        internal static string Label_InstrumentSN {
            get {
                return ResourceManager.GetString("Label_InstrumentSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Number:.
        /// </summary>
        internal static string Label_JobNumber {
            get {
                return ResourceManager.GetString("Label_JobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number:.
        /// </summary>
        internal static string Label_PartNumber {
            get {
                return ResourceManager.GetString("Label_PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed By:.
        /// </summary>
        internal static string Label_PerformedBy {
            get {
                return ResourceManager.GetString("Label_PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Pump:.
        /// </summary>
        internal static string Label_PumpAccessory {
            get {
                return ResourceManager.GetString("Label_PumpAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By:.
        /// </summary>
        internal static string Label_ReceivedBy {
            get {
                return ResourceManager.GetString("Label_ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Date:.
        /// </summary>
        internal static string Label_SetupDate {
            get {
                return ResourceManager.GetString("Label_SetupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Technician:.
        /// </summary>
        internal static string Label_SetupTechnician {
            get {
                return ResourceManager.GetString("Label_SetupTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon Monoxide Sensor.
        /// </summary>
        internal static string S0001 {
            get {
                return ResourceManager.GetString("S0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Sulfide Sensor.
        /// </summary>
        internal static string S0002 {
            get {
                return ResourceManager.GetString("S0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfur Dioxide Sensor.
        /// </summary>
        internal static string S0003 {
            get {
                return ResourceManager.GetString("S0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen Dioxide Sensor.
        /// </summary>
        internal static string S0004 {
            get {
                return ResourceManager.GetString("S0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine Sensor.
        /// </summary>
        internal static string S0005 {
            get {
                return ResourceManager.GetString("S0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine Dioxide Sensor.
        /// </summary>
        internal static string S0006 {
            get {
                return ResourceManager.GetString("S0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Cyanide Sensor.
        /// </summary>
        internal static string S0007 {
            get {
                return ResourceManager.GetString("S0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphine Sensor.
        /// </summary>
        internal static string S0008 {
            get {
                return ResourceManager.GetString("S0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Sensor.
        /// </summary>
        internal static string S0009 {
            get {
                return ResourceManager.GetString("S0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon Dioxide Sensor.
        /// </summary>
        internal static string S0011 {
            get {
                return ResourceManager.GetString("S0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitric Oxide Sensor.
        /// </summary>
        internal static string S0012 {
            get {
                return ResourceManager.GetString("S0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia Sensor.
        /// </summary>
        internal static string S0013 {
            get {
                return ResourceManager.GetString("S0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Chloride Sensor.
        /// </summary>
        internal static string S0014 {
            get {
                return ResourceManager.GetString("S0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozone Sensor.
        /// </summary>
        internal static string S0015 {
            get {
                return ResourceManager.GetString("S0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosgene Sensor.
        /// </summary>
        internal static string S0016 {
            get {
                return ResourceManager.GetString("S0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen Fluoride Sensor.
        /// </summary>
        internal static string S0017 {
            get {
                return ResourceManager.GetString("S0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR-Methane Sensor.
        /// </summary>
        internal static string S0018 {
            get {
                return ResourceManager.GetString("S0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustible-PPM Sensor.
        /// </summary>
        internal static string S0019 {
            get {
                return ResourceManager.GetString("S0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen Sensor.
        /// </summary>
        internal static string S0020 {
            get {
                return ResourceManager.GetString("S0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustible-CH4 Sensor.
        /// </summary>
        internal static string S0021 {
            get {
                return ResourceManager.GetString("S0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustible-LEL Sensor.
        /// </summary>
        internal static string S0022 {
            get {
                return ResourceManager.GetString("S0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methane IR LEL.
        /// </summary>
        internal static string S0024 {
            get {
                return ResourceManager.GetString("S0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentane Sensor.
        /// </summary>
        internal static string S0026 {
            get {
                return ResourceManager.GetString("S0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propane Sensor.
        /// </summary>
        internal static string S0027 {
            get {
                return ResourceManager.GetString("S0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID Sensor.
        /// </summary>
        internal static string S0050 {
            get {
                return ResourceManager.GetString("S0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethylene Oxide Sensor.
        /// </summary>
        internal static string S0081 {
            get {
                return ResourceManager.GetString("S0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrocarbon Sensor.
        /// </summary>
        internal static string S0248 {
            get {
                return ResourceManager.GetString("S0248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump Certificate.
        /// </summary>
        internal static string Title_BumpCertificate {
            get {
                return ResourceManager.GetString("Title_BumpCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Certificate.
        /// </summary>
        internal static string Title_CalibrationCertificate {
            get {
                return ResourceManager.GetString("Title_CalibrationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string Value_Aborted {
            get {
                return ResourceManager.GetString("Value_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Value_BumpFailedFreshAirFailed {
            get {
                return ResourceManager.GetString("Value_BumpFailedFreshAirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Low.
        /// </summary>
        internal static string Value_BumpFailedFreshAirPassed {
            get {
                return ResourceManager.GetString("Value_BumpFailedFreshAirPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed High.
        /// </summary>
        internal static string Value_BumpPassedFreshAirFailed {
            get {
                return ResourceManager.GetString("Value_BumpPassedFreshAirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Value_Failed {
            get {
                return ResourceManager.GetString("Value_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Air.
        /// </summary>
        internal static string Value_FreshAir {
            get {
                return ResourceManager.GetString("Value_FreshAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Value_Installed {
            get {
                return ResourceManager.GetString("Value_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marginal.
        /// </summary>
        internal static string Value_Marginal {
            get {
                return ResourceManager.GetString("Value_Marginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Value_NA {
            get {
                return ResourceManager.GetString("Value_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed High.
        /// </summary>
        internal static string Value_O2RecoveryFailed {
            get {
                return ResourceManager.GetString("Value_O2RecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string Value_Passed {
            get {
                return ResourceManager.GetString("Value_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Value_Skipped {
            get {
                return ResourceManager.GetString("Value_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        internal static string Value_Uninstalled {
            get {
                return ResourceManager.GetString("Value_Uninstalled", resourceCulture);
            }
        }
    }
}
